PROMPT ==== 01_tables.sql  (LOS base tables - written 2019, DB team) ====

CREATE TABLE LOAN_STATUS (
    STATUS_CODE   VARCHAR2(10)  NOT NULL,
    DESCRIPTION   VARCHAR2(100) NOT NULL,
    CONSTRAINT LOAN_STATUS_PK PRIMARY KEY (STATUS_CODE)
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID   NUMBER        NOT NULL,
    FULL_NAME     VARCHAR2(200) NOT NULL,
    MOBILE        VARCHAR2(15),
    CREATED_ON    DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE LOAN_APPLICATION (
    APP_ID        NUMBER        NOT NULL,
    CUSTOMER_ID   NUMBER        NOT NULL,
    AMOUNT        NUMBER(12,2)  NOT NULL,
    STATUS_CODE   VARCHAR2(10)  DEFAULT 'NEW' NOT NULL,
    CREATED_ON    DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT LOAN_APPLICATION_PK PRIMARY KEY (APP_ID),
    CONSTRAINT LOAN_APP_CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID),
    CONSTRAINT LOAN_APP_STATUS_FK   FOREIGN KEY (STATUS_CODE) REFERENCES LOAN_STATUS (STATUS_CODE)
);

CREATE INDEX LOAN_APP_CUSTOMER_IX ON LOAN_APPLICATION (CUSTOMER_ID);

CREATE TABLE AUDIT_LOG (
    LOG_ID        NUMBER        NOT NULL,
    TABLE_NAME    VARCHAR2(30)  NOT NULL,
    ACTION        VARCHAR2(10)  NOT NULL,
    KEY_VALUE     VARCHAR2(100),
    LOGGED_ON     DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT AUDIT_LOG_PK PRIMARY KEY (LOG_ID)
);
