PROMPT ==== 02_sequences.sql ====

CREATE SEQUENCE CUSTOMER_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE LOAN_APP_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AUDIT_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
