PROMPT ==== 03_reference_data.sql ====
SET DEFINE OFF

INSERT INTO LOAN_STATUS (STATUS_CODE, DESCRIPTION) VALUES ('NEW',       'Application received');
INSERT INTO LOAN_STATUS (STATUS_CODE, DESCRIPTION) VALUES ('APPROVED',  'Approved by credit team');
INSERT INTO LOAN_STATUS (STATUS_CODE, DESCRIPTION) VALUES ('REJECTED',  'Rejected');
INSERT INTO LOAN_STATUS (STATUS_CODE, DESCRIPTION) VALUES ('DISBURSED', 'Amount paid out');
COMMIT;
