PROMPT ==== 04_functions_procedures.sql ====

CREATE OR REPLACE FUNCTION GET_CUSTOMER_NAME (P_CUSTOMER_ID IN NUMBER)
RETURN VARCHAR2
AS
    V_NAME CUSTOMER.FULL_NAME%TYPE;
BEGIN
    SELECT FULL_NAME INTO V_NAME FROM CUSTOMER WHERE CUSTOMER_ID = P_CUSTOMER_ID;
    RETURN V_NAME;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END GET_CUSTOMER_NAME;
/
SHOW ERRORS

CREATE OR REPLACE PROCEDURE ADD_CUSTOMER (
    P_FULL_NAME   IN  VARCHAR2,
    P_MOBILE      IN  VARCHAR2,
    P_CUSTOMER_ID OUT NUMBER
)
AS
BEGIN
    -- CUSTOMER_ID is filled by trigger CUSTOMER_BI
    INSERT INTO CUSTOMER (FULL_NAME, MOBILE)
    VALUES (P_FULL_NAME, P_MOBILE)
    RETURNING CUSTOMER_ID INTO P_CUSTOMER_ID;
END ADD_CUSTOMER;
/
SHOW ERRORS
