PROMPT ==== 05_packages.sql ====

CREATE OR REPLACE PACKAGE LOAN_PKG
AS
    FUNCTION CREATE_APPLICATION (P_CUSTOMER_ID IN NUMBER, P_AMOUNT IN NUMBER) RETURN NUMBER;
    PROCEDURE APPROVE (P_APP_ID IN NUMBER);
END LOAN_PKG;
/
SHOW ERRORS

CREATE OR REPLACE PACKAGE BODY LOAN_PKG
AS
    FUNCTION CREATE_APPLICATION (P_CUSTOMER_ID IN NUMBER, P_AMOUNT IN NUMBER) RETURN NUMBER
    AS
        V_APP_ID NUMBER := LOAN_APP_SEQ.NEXTVAL;
    BEGIN
        INSERT INTO LOAN_APPLICATION (APP_ID, CUSTOMER_ID, AMOUNT)
        VALUES (V_APP_ID, P_CUSTOMER_ID, P_AMOUNT);
        RETURN V_APP_ID;
    END CREATE_APPLICATION;

    PROCEDURE APPROVE (P_APP_ID IN NUMBER)
    AS
    BEGIN
        UPDATE LOAN_APPLICATION SET STATUS_CODE = 'APPROVED' WHERE APP_ID = P_APP_ID;
    END APPROVE;
END LOAN_PKG;
/
SHOW ERRORS
