PROMPT ==== 06_views.sql ====

CREATE OR REPLACE VIEW V_LOAN_SUMMARY AS
SELECT LA.APP_ID,
       C.CUSTOMER_ID,
       C.FULL_NAME,
       LA.AMOUNT,
       LS.DESCRIPTION AS STATUS,
       LA.CREATED_ON
  FROM LOAN_APPLICATION LA
  JOIN CUSTOMER    C  ON C.CUSTOMER_ID  = LA.CUSTOMER_ID
  JOIN LOAN_STATUS LS ON LS.STATUS_CODE = LA.STATUS_CODE;
