PROMPT ==== 07_triggers.sql ====

CREATE OR REPLACE TRIGGER CUSTOMER_BI
BEFORE INSERT ON CUSTOMER
FOR EACH ROW
BEGIN
    IF :NEW.CUSTOMER_ID IS NULL THEN
        :NEW.CUSTOMER_ID := CUSTOMER_SEQ.NEXTVAL;
    END IF;
END;
/
SHOW ERRORS

CREATE OR REPLACE TRIGGER LOAN_APPLICATION_AUD
AFTER INSERT OR UPDATE ON LOAN_APPLICATION
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_LOG (LOG_ID, TABLE_NAME, ACTION, KEY_VALUE)
    VALUES (AUDIT_LOG_SEQ.NEXTVAL,
            'LOAN_APPLICATION',
            CASE WHEN INSERTING THEN 'INSERT' ELSE 'UPDATE' END,
            TO_CHAR(:NEW.APP_ID));
END;
/
SHOW ERRORS
