PROMPT ==== 10_sample_data.sql  (TEST DATA - Dev only, never Prod) ====
SET DEFINE OFF

DECLARE
    V_CUST NUMBER;
    V_APP  NUMBER;
BEGIN
    ADD_CUSTOMER('Asha Patil',  '9800000001', V_CUST);
    V_APP := LOAN_PKG.CREATE_APPLICATION(V_CUST, 250000);
    LOAN_PKG.APPROVE(V_APP);

    ADD_CUSTOMER('Ravi Kumar',  '9800000002', V_CUST);
    V_APP := LOAN_PKG.CREATE_APPLICATION(V_CUST, 100000);
END;
/
COMMIT;
